# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wms.proto
# pyright: reportUndefinedVariable=false
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\twms.proto\x12\x03wms\"\x82\x01\n\nWMSMessage\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x1b\n\x05order\x18\x02 \x01(\x0b\x32\n.wms.OrderH\x00\x12*\n\rstatus_update\x18\x03 \x01(\x0b\x32\x11.wms.StatusUpdateH\x00\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\x42\t\n\x07message\"r\n\x05Order\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x12\n\ncustomerId\x18\x02 \x01(\t\x12\x1c\n\x04item\x18\x03 \x03(\x0b\x32\x0e.wms.OrderItem\x12\x14\n\x0ctotal_amount\x18\x04 \x01(\x01\x12\x10\n\x08priority\x18\x05 \x01(\t\"<\n\tOrderItem\x12\x0e\n\x06itemId\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x01\"I\n\x0cStatusUpdate\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x18\n\x10reference_number\x18\x03 \x01(\t\"l\n\x0bWMSResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07orderId\x18\x03 \x01(\t\x12\x18\n\x10reference_number\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wms_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WMSMESSAGE._serialized_start=19
  _WMSMESSAGE._serialized_end=149
  _ORDER._serialized_start=151
  _ORDER._serialized_end=265
  _ORDERITEM._serialized_start=267
  _ORDERITEM._serialized_end=327
  _STATUSUPDATE._serialized_start=329
  _STATUSUPDATE._serialized_end=402
  _WMSRESPONSE._serialized_start=404
  _WMSRESPONSE._serialized_end=512
# @@protoc_insertion_point(module_scope)
